export const ACHIEVEMENTS = [
    {
        id: 'fitness_freak',
        title: 'Fitness Freak',
        description: 'Welcome to CampusTitan! You’re officially a part of the fitness movement.',
        icon: require('../../assets/images/badges/fitness_freak.png'),
        type: 'starter',
        color: '#06B6D4',
        gradient: ['#06B6D4', '#6366F1', '#A78BFA'],
    },
    {
        id: 'step_smasher',
        title: 'Step Smasher',
        description: 'Walk over 10,000 steps in a single day.',
        icon: require('../../assets/images/badges/step_smasher.png'),
        type: 'fitness',
        color: '#6366F1',
        gradient: ['#6366F1', '#818CF8'],
    },
    {
        id: 'calorie_crusader',
        title: 'Calorie Crusader',
        description: 'Log your meals for 7 consecutive days.',
        icon: require('../../assets/images/badges/calorie_crusader.png'),
        type: 'nutrition',
        color: '#F59E0B',
        gradient: ['#F59E0B', '#FB923C'],
    },
    {
        id: 'mindfulness_master',
        title: 'Mindfulness Master',
        description: 'Log your mood and mental well-being for 3 consecutive days.',
        icon: require('../../assets/images/badges/mindfulness_master.png'),
        type: 'mental',
        color: '#8B5CF6',
        gradient: ['#8B5CF6', '#A78BFA'],
    },
    {
        id: 'consistency_king',
        title: 'Consistency King',
        description: 'Complete at least 5 activities in a single week.',
        icon: require('../../assets/images/badges/consistency_king.png'),
        type: 'fitness',
        color: '#10B981',
        gradient: ['#10B981', '#34D399'],
    },
    {
        id: 'burn_baby_burn',
        title: 'Burn Baby Burn',
        description: 'Burn more than 500 calories in a single workout session.',
        icon: require('../../assets/images/badges/burn_baby_burn.png'),
        type: 'fitness',
        color: '#EF4444',
        gradient: ['#EF4444', '#F87171'],
    },
    {
        id: 'night_owl',
        title: 'Night Owl',
        description: 'Log a journal entry after 11:00 PM.',
        icon: require('../../assets/images/badges/night_owl.png'),
        type: 'mental',
        color: '#3B82F6',
        gradient: ['#3B82F6', '#60A5FA'],
    },
    {
        id: 'early_bird',
        title: 'Early Bird',
        description: 'Complete an activity before 8:00 AM.',
        icon: require('../../assets/images/badges/early_bird.png'),
        type: 'fitness',
        color: '#F97316',
        gradient: ['#F97316', '#FB923C'],
    },
];
